version: "3"
services:
  speech-to-do-app:
    image: speechtodo.azurecr.io/speech-to-do-app
    build: ./frontend/.
    ports:
      - "443:443"
  speech-to-do-backend:
    image: speechtodo.azurecr.io/speech-to-do-backend
    build: ./backend/.
    ports:
      - "5001:5000"
